# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 23:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('people', '0002_auto_20170423_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_max', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(300)])),
                ('round', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('time_seconds', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('draw', models.BooleanField(default=False)),
                ('no_contest', models.BooleanField(default=False)),
                ('method', models.CharField(blank=True, choices=[('KO', 'Knockout'), ('TKO', 'Technical Knockout'), ('UD', 'Unanimous Decision'), ('SD', 'Split Decision'), ('MD', 'Majority Decision'), ('ED', 'Extra Round Decision'), ('UDr', 'Unanimous Draw'), ('MDr', 'Majority Draw'), ('NC', 'No Contest')], max_length=3)),
                ('method_detail', models.CharField(blank=True, max_length=64)),
                ('video', models.URLField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Card')),
                ('fighter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='people.Fighter')),
                ('fighter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='people.Fighter')),
                ('referee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='people.Referee')),
                ('title', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.Title')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-card__event__date'],
            },
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('loser_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('judge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='people.Judge')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
            ],
        ),
    ]
