# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 00:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20170423_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
