# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 23:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fighter',
            name='boxing_record',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='mma_record',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='height',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='reach',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
