# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 00:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170423_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='reach',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
